<a href="https://colab.research.google.com/github/DMULE2213/keras_tuner/blob/main/keral_hyper_parameter_tunning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd

In [29]:
df= pd.read_csv('/diabetes.csv')

In [30]:
 df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [31]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [32]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [35]:
x.shape

(768, 8)

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [139]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [38]:
model = Sequential()

model.add(Dense(32,activation='relu', input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
model.fit(x_train, y_train, batch_size=32, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.4442 - loss: 0.7898 - val_accuracy: 0.5519 - val_loss: 0.7262
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6294 - loss: 0.6920 - val_accuracy: 0.6299 - val_loss: 0.6681
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6701 - loss: 0.6346 - val_accuracy: 0.6753 - val_loss: 0.6242
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6634 - loss: 0.6086 - val_accuracy: 0.6948 - val_loss: 0.5895
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6962 - loss: 0.5845 - val_accuracy: 0.7208 - val_loss: 0.5613
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6963 - loss: 0.5769 - val_accuracy: 0.7208 - val_loss: 0.5385
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7468 - loss: 0.5276 - val_accuracy: 0.7338 - val_loss: 0.5199
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7539 - loss: 0.5213 - val_accuracy: 0.7403 - val_loss: 0.5049
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7379 - loss: 0.4959 - val_accuracy: 0.7403 - val_loss: 0.4930
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7409 - loss: 0.5032 - val_accuracy: 0.7662 - val_loss: 0.4831
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7371 - loss: 0.5137 - val_accuracy: 0.7727 - val_loss: 0.4753
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7809 - loss: 0.4658 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7485 - loss: 0.5062 - val_accuracy: 0.8052 - val_loss: 0.4635
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7788 - loss: 0.4781 - val_accuracy: 0.8117 - val_loss: 0.4603
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7755 - loss: 0.4566 - val_accuracy: 0.8052 - val_loss: 0.4562
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7775 - loss: 0.4773 - val_accuracy: 0.8052 - val_loss: 0.4532
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7705 - loss: 0.4748 - val_accuracy: 0.8052 - val_loss: 0.4522
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7532 - loss: 0.4837 - val_accuracy: 0.8052 - val_loss: 0.4489
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7319 - loss: 0.4905 - val_accuracy: 0.8052 - val_loss: 0.4483
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7924 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4458
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7527 - loss: 0.4849 - val_accuracy: 0.8117 - val_loss: 0.4457
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7875 - loss: 0.4531 - val_accuracy: 0.8117 - val_loss: 0.4462
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8032 - loss: 0.4330 - val_accuracy: 0.8117 - val_loss: 0.4451
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7613 - loss: 0.4782 - val_accuracy: 0.8117 - val_loss: 0.4442
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4155 - val_accuracy: 0.8182 - val_loss: 0.4431
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7919 - loss: 0.4506 - val_accuracy: 0.8117 - val_loss: 0.4447
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7653 - loss: 0.4665 - val_accuracy: 0.8052 - val_loss: 0.4440
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7859 - loss: 0.4395 - val_accuracy: 0.8052 - val_loss: 0.4441
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7959 - loss: 0.4473 - val_accuracy: 0.8182 - val_loss: 0.4456
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7774 - loss: 0.4593 - val_accuracy: 0.8052 - val_loss: 0.4447
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7861 - loss: 0.4593 - val_accuracy: 0.8052 - val_loss: 0.4447
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7732 - loss: 0.4426 - val_accuracy: 0.8117 - val_loss: 0.4441
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4222 - val_accuracy: 0.8182 - val_loss: 0.4439
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7902 - loss: 0.4434 - val_accuracy: 0.8247 - val_loss: 0.4436
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7712 - loss: 0.4430 - val_accuracy: 0.8247 - val_loss: 0.4433
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7792 - loss: 0.4652 - val_accuracy: 0.8247 - val_loss: 0.4423
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7802 - loss: 0.4484 - val_accuracy: 0.8247 - val_loss: 0.4440
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7854 - loss: 0.4490 - val_accuracy: 0.8247 - val_loss: 0.4437
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8107 - loss: 0.4108 - val_accuracy: 0.8247 - val_loss: 0.4435
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7718 - loss: 0.4588 - val_accuracy: 0.8247 - val_loss: 0.4434
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7820 - loss: 0.4447 - val_accuracy: 0.8247 - val_loss: 0.4438
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7869 - loss: 0.4208 - val_accuracy: 0.8182 - val_loss: 0.4442
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8010 - loss: 0.4308 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7889 - loss: 0.4339 - val_accuracy: 0.8182 - val_loss: 0.4454
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7841 - loss: 0.4498 - val_accuracy: 0.8182 - val_loss: 0.4460
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7768 - loss: 0.4512 - val_accuracy: 0.8117 - val_loss: 0.4469
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4527 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7893 - loss: 0.4500 - val_accuracy: 0.8182 - val_loss: 0.4458
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8059 - loss: 0.4466 - val_accuracy: 0.8182 - val_loss: 0.4445
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7776 - loss: 0.4476 - val_accuracy: 0.8182 - val_loss: 0.4451
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7911 - loss: 0.4176 - val_accuracy: 0.8117 - val_loss: 0.4467
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4485
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8088 - loss: 0.4368 - val_accuracy: 0.8117 - val_loss: 0.4456
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4370 - val_accuracy: 0.8117 - val_loss: 0.4466
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8096 - loss: 0.4185 - val_accuracy: 0.8117 - val_loss: 0.4460
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7959 - loss: 0.4299 - val_accuracy: 0.8182 - val_loss: 0.4463
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7885 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4460
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8047 - loss: 0.4123 - val_accuracy: 0.8182 - val_loss: 0.4461
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8036 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4478
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8064 - loss: 0.4151 - val_accuracy: 0.8117 - val_loss: 0.4478
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7938 - loss: 0.4394 - val_accuracy: 0.8117 - val_loss: 0.4486
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8093 - loss: 0.4238 - val_accuracy: 0.8117 - val_loss: 0.4490
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7906 - loss: 0.4536 - val_accuracy: 0.8117 - val_loss: 0.4501
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7864 - loss: 0.4317 - val_accuracy: 0.8117 - val_loss: 0.4493
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8155 - loss: 0.4126 - val_accuracy: 0.8117 - val_loss: 0.4487
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8103 - loss: 0.4094 - val_accuracy: 0.8117 - val_loss: 0.4480
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7909 - loss: 0.4469 - val_accuracy: 0.8117 - val_loss: 0.4505
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8122 - loss: 0.4128 - val_accuracy: 0.8117 - val_loss: 0.4496
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8183 - loss: 0.4161 - val_accuracy: 0.8117 - val_loss: 0.4484
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8234 - loss: 0.4180 - val_accuracy: 0.8117 - val_loss: 0.4478
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8039 - loss: 0.4495 - val_accuracy: 0.8182 - val_loss: 0.4482
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7797 - loss: 0.4378 - val_accuracy: 0.8117 - val_loss: 0.4475
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4263 - val_accuracy: 0.8117 - val_loss: 0.4470
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8060 - loss: 0.4204 - val_accuracy: 0.8182 - val_loss: 0.4466
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8060 - loss: 0.4271 - val_accuracy: 0.8117 - val_loss: 0.4491
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7933 - loss: 0.4102 - val_accuracy: 0.8117 - val_loss: 0.4484
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8098 - loss: 0.4088 - val_accuracy: 0.8117 - val_loss: 0.4486
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8091 - loss: 0.4227 - val_accuracy: 0.8117 - val_loss: 0.4475
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4180 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8130 - loss: 0.4073 - val_accuracy: 0.8117 - val_loss: 0.4507
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8362 - loss: 0.3989 - val_accuracy: 0.8182 - val_loss: 0.4503
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7790 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4496
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8052 - loss: 0.4171 - val_accuracy: 0.8182 - val_loss: 0.4491
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8022 - loss: 0.4422 - val_accuracy: 0.8117 - val_loss: 0.4514
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8283 - loss: 0.4047 - val_accuracy: 0.8117 - val_loss: 0.4537
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7864 - loss: 0.4232 - val_accuracy: 0.8117 - val_loss: 0.4527
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8040 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4512
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8359 - loss: 0.4168 - val_accuracy: 0.8247 - val_loss: 0.4515
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8191 - loss: 0.4189 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8043 - loss: 0.4206 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8239 - loss: 0.3929 - val_accuracy: 0.8182 - val_loss: 0.4533
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8179 - loss: 0.4096 - val_accuracy: 0.8247 - val_loss: 0.4544
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7868 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4554
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8039 - loss: 0.4346 - val_accuracy: 0.8247 - val_loss: 0.4545
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.3854 - val_accuracy: 0.8052 - val_loss: 0.4550
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7901 - loss: 0.4437 - val_accuracy: 0.8182 - val_loss: 0.4571
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8171 - loss: 0.4197 - val_accuracy: 0.8117 - val_loss: 0.4567
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8250 - loss: 0.3903 - val_accuracy: 0.8117 - val_loss: 0.4540
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8129 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4561
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8040 - loss: 0.4208 - val_accuracy: 0.8182 - val_loss: 0.4564

In [56]:
import keras_tuner as kt

In [60]:
tuner.search(x_train,y_train, epochs=5,validation_data=(x_test, y_test))

In [81]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(32,activation='relu', input_dim=8))

  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta']
                        )
  model.compile(optimizer= optimizer,loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [82]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [83]:
tuner.search(x_train,y_train,epochs=15,validation_data=(x_test,y_test))

In [84]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [85]:
model = tuner.get_best_models(num_models=1)[0]

In [90]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [91]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7715 - loss: 0.4826 - val_accuracy: 0.7792 - val_loss: 0.4491
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7444 - loss: 0.5069 - val_accuracy: 0.7922 - val_loss: 0.4458
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7868 - loss: 0.4569 - val_accuracy: 0.7922 - val_loss: 0.4440
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7839 - loss: 0.4577 - val_accuracy: 0.8052 - val_loss: 0.4412
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7806 - loss: 0.4776 - val_accuracy: 0.8052 - val_loss: 0.4386
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7820 - loss: 0.4615 - val_accuracy: 0.8052 - val_loss: 0.4374
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7782 - loss: 0.4699 - val_accuracy: 0.8052 - val_loss: 0.4359
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4568 - val_accuracy: 0.8052 - val_loss: 0.4356
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7917 - loss: 0.4574 - val_accuracy: 0.8052 - val_loss: 0.4332
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7722 - loss: 0.4762 - val_accuracy: 0.7987 - val_loss: 0.4328
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7998 - loss: 0.4561 - val_accuracy: 0.7987 - val_loss: 0.4327
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7894 - loss: 0.4424 - val_accuracy: 0.7987 - val_loss: 0.4341
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7714 - loss: 0.4766 - val_accuracy: 0.7987 - val_loss: 0.4357
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7665 - loss: 0.4563 - val_accuracy: 0.7987 - val_loss: 0.4336
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8075 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4321
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7768 - loss: 0.4756 - val_accuracy: 0.7987 - val_loss: 0.4324
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8010 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4335
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4317
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4337 - val_accuracy: 0.8052 - val_loss: 0.4341
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7855 - loss: 0.4403 - val_accuracy: 0.7987 - val_loss: 0.4346
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7971 - loss: 0.4389 - val_accuracy: 0.7987 - val_loss: 0.4360
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8015 - loss: 0.4386 - val_accuracy: 0.8052 - val_loss: 0.4347
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4349 - val_accuracy: 0.7987 - val_loss: 0.4352
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7810 - loss: 0.4554 - val_accuracy: 0.8052 - val_loss: 0.4344
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7664 - loss: 0.4608 - val_accuracy: 0.8052 - val_loss: 0.4338
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7921 - loss: 0.4346 - val_accuracy: 0.8052 - val_loss: 0.4349
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7726 - loss: 0.4634 - val_accuracy: 0.8052 - val_loss: 0.4352
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7965 - loss: 0.4308 - val_accuracy: 0.7987 - val_loss: 0.4358
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8016 - loss: 0.4359 - val_accuracy: 0.7987 - val_loss: 0.4353
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8180 - loss: 0.4291 - val_accuracy: 0.8052 - val_loss: 0.4365
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7859 - loss: 0.4322 - val_accuracy: 0.8052 - val_loss: 0.4376
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7979 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4406
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4294 - val_accuracy: 0.8052 - val_loss: 0.4388
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8130 - loss: 0.4112 - val_accuracy: 0.8052 - val_loss: 0.4379
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7918 - loss: 0.4475 - val_accuracy: 0.8052 - val_loss: 0.4380
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7906 - loss: 0.4358 - val_accuracy: 0.8052 - val_loss: 0.4377
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7820 - loss: 0.4482 - val_accuracy: 0.8052 - val_loss: 0.4369
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8009 - loss: 0.4235 - val_accuracy: 0.8117 - val_loss: 0.4360
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8014 - loss: 0.4278 - val_accuracy: 0.8052 - val_loss: 0.4361
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7984 - loss: 0.4358 - val_accuracy: 0.8052 - val_loss: 0.4364
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7954 - loss: 0.4449 - val_accuracy: 0.8052 - val_loss: 0.4372
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7923 - loss: 0.4390 - val_accuracy: 0.8052 - val_loss: 0.4374
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7986 - loss: 0.4298 - val_accuracy: 0.8052 - val_loss: 0.4374
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7909 - loss: 0.4113 - val_accuracy: 0.8117 - val_loss: 0.4367
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8162 - loss: 0.4233 - val_accuracy: 0.8117 - val_loss: 0.4393
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7741 - loss: 0.4506 - val_accuracy: 0.8117 - val_loss: 0.4384
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.4313 - val_accuracy: 0.8117 - val_loss: 0.4386
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4462 - val_accuracy: 0.8117 - val_loss: 0.4395
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8042 - loss: 0.4161 - val_accuracy: 0.8117 - val_loss: 0.4406
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8198 - loss: 0.4256 - val_accuracy: 0.8052 - val_loss: 0.4380
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8302 - loss: 0.3969 - val_accuracy: 0.8117 - val_loss: 0.4386
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4157 - val_accuracy: 0.8117 - val_loss: 0.4393
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7965 - loss: 0.4506 - val_accuracy: 0.8117 - val_loss: 0.4379
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4294 - val_accuracy: 0.8117 - val_loss: 0.4406
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4468 - val_accuracy: 0.8182 - val_loss: 0.4413
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8028 - loss: 0.4231 - val_accuracy: 0.8182 - val_loss: 0.4416
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8021 - loss: 0.4094 - val_accuracy: 0.8182 - val_loss: 0.4437
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7968 - loss: 0.4393 - val_accuracy: 0.8182 - val_loss: 0.4414
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8026 - loss: 0.4253 - val_accuracy: 0.8182 - val_loss: 0.4418
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8195 - loss: 0.4149 - val_accuracy: 0.8182 - val_loss: 0.4423
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8115 - loss: 0.4156 - val_accuracy: 0.8182 - val_loss: 0.4423
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7974 - loss: 0.4278 - val_accuracy: 0.8182 - val_loss: 0.4438
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7935 - loss: 0.4208 - val_accuracy: 0.8182 - val_loss: 0.4413
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8101 - loss: 0.4110 - val_accuracy: 0.8182 - val_loss: 0.4401
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8055 - loss: 0.4111 - val_accuracy: 0.8247 - val_loss: 0.4400
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8138 - loss: 0.4069 - val_accuracy: 0.8182 - val_loss: 0.4391
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8124 - loss: 0.4325 - val_accuracy: 0.8182 - val_loss: 0.4413
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7953 - loss: 0.4322 - val_accuracy: 0.8182 - val_loss: 0.4412
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8076 - loss: 0.4134 - val_accuracy: 0.8247 - val_loss: 0.4436
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7847 - loss: 0.4385 - val_accuracy: 0.8247 - val_loss: 0.4426
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4544 - val_accuracy: 0.8247 - val_loss: 0.4435
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8129 - loss: 0.3922 - val_accuracy: 0.8247 - val_loss: 0.4448
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8250 - loss: 0.3952 - val_accuracy: 0.8247 - val_loss: 0.4436
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7897 - loss: 0.4517 - val_accuracy: 0.8247 - val_loss: 0.4446
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3922 - val_accuracy: 0.8182 - val_loss: 0.4443
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8086 - loss: 0.4297 - val_accuracy: 0.8182 - val_loss: 0.4442
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4491 - val_accuracy: 0.8182 - val_loss: 0.4456
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7824 - loss: 0.4385 - val_accuracy: 0.8117 - val_loss: 0.4461
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8173 - loss: 0.4023 - val_accuracy: 0.8182 - val_loss: 0.4462
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7960 - loss: 0.4283 - val_accuracy: 0.8182 - val_loss: 0.4454
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7875 - loss: 0.4639 - val_accuracy: 0.8182 - val_loss: 0.4457
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8042 - loss: 0.4138 - val_accuracy: 0.8182 - val_loss: 0.4462
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7920 - loss: 0.4316 - val_accuracy: 0.8182 - val_loss: 0.4473
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8118 - loss: 0.4021 - val_accuracy: 0.8182 - val_loss: 0.4485
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4337 - val_accuracy: 0.8182 - val_loss: 0.4464
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4189 - val_accuracy: 0.8182 - val_loss: 0.4461
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8248 - loss: 0.4058 - val_accuracy: 0.8182 - val_loss: 0.4466
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8148 - loss: 0.4010 - val_accuracy: 0.8182 - val_loss: 0.4474
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.3987 - val_accuracy: 0.8117 - val_loss: 0.4477
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.4149 - val_accuracy: 0.8117 - val_loss: 0.4487
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8069 - loss: 0.4049 - val_accuracy: 0.8117 - val_loss: 0.4489
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8256 - loss: 0.4014 - val_accuracy: 0.8117 - val_loss: 0.4472
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8323 - loss: 0.3797 - val_accuracy: 0.8182 - val_loss: 0.4474
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.4078 - val_accuracy: 0.8117 - val_loss: 0.4491

In [96]:
def model_build(hp):

  model = Sequential()
  units = hp.Int('units',8, 128, step=8)
  model.add(Dense(units, activation='relu', input_dim=8))
  model.add(Dense(units,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [97]:
tuner = kt.RandomSearch(model_build,objective='val_accuracy',max_trials=5, directory='mkdir', project_name = 'sumit')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [100]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [101]:
tuner.get_best_hyperparameters()[0].values

{'units': 72}

In [102]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [104]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.7817 - loss: 0.4512 - val_accuracy: 0.8182 - val_loss: 0.4187
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7941 - loss: 0.4434 - val_accuracy: 0.8117 - val_loss: 0.4143
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7807 - loss: 0.4540 - val_accuracy: 0.8377 - val_loss: 0.4256
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7867 - loss: 0.4325 - val_accuracy: 0.8312 - val_loss: 0.4279
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7758 - loss: 0.4460 - val_accuracy: 0.8312 - val_loss: 0.4282
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7943 - loss: 0.4374 - val_accuracy: 0.8247 - val_loss: 0.4262
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7807 - loss: 0.4364 - val_accuracy: 0.8312 - val_loss: 0.4344
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4251 - val_accuracy: 0.8247 - val_loss: 0.4261
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7696 - loss: 0.4451 - val_accuracy: 0.8117 - val_loss: 0.4257
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7705 - loss: 0.4561 - val_accuracy: 0.8377 - val_loss: 0.4388
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7840 - loss: 0.4560 - val_accuracy: 0.8182 - val_loss: 0.4286
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8019 - loss: 0.4130 - val_accuracy: 0.8182 - val_loss: 0.4281
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4074 - val_accuracy: 0.8182 - val_loss: 0.4348
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8021 - loss: 0.4103 - val_accuracy: 0.8247 - val_loss: 0.4337
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7861 - loss: 0.4363 - val_accuracy: 0.8117 - val_loss: 0.4414
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8008 - loss: 0.4257 - val_accuracy: 0.8052 - val_loss: 0.4400
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4226 - val_accuracy: 0.8182 - val_loss: 0.4374
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.4015 - val_accuracy: 0.8312 - val_loss: 0.4369
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8136 - loss: 0.4005 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.4007 - val_accuracy: 0.8052 - val_loss: 0.4469
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8113 - loss: 0.3726 - val_accuracy: 0.8247 - val_loss: 0.4397
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8161 - loss: 0.4032 - val_accuracy: 0.8312 - val_loss: 0.4432
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8285 - loss: 0.3819 - val_accuracy: 0.8377 - val_loss: 0.4467
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8252 - loss: 0.3786 - val_accuracy: 0.8247 - val_loss: 0.4468
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8259 - loss: 0.3909 - val_accuracy: 0.8312 - val_loss: 0.4441
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8394 - loss: 0.3835 - val_accuracy: 0.8312 - val_loss: 0.4443
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8097 - loss: 0.4051 - val_accuracy: 0.8182 - val_loss: 0.4567
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8191 - loss: 0.4100 - val_accuracy: 0.8312 - val_loss: 0.4479
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8464 - loss: 0.3700 - val_accuracy: 0.8182 - val_loss: 0.4499
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8135 - loss: 0.3859 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8335 - loss: 0.3586 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8610 - loss: 0.3279 - val_accuracy: 0.8182 - val_loss: 0.4628
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8603 - loss: 0.3671 - val_accuracy: 0.8117 - val_loss: 0.4651
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8397 - loss: 0.3611 - val_accuracy: 0.8052 - val_loss: 0.4516
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8362 - loss: 0.3747 - val_accuracy: 0.8182 - val_loss: 0.4661
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8386 - loss: 0.3583 - val_accuracy: 0.8117 - val_loss: 0.4675
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8369 - loss: 0.3766 - val_accuracy: 0.8377 - val_loss: 0.4561
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8499 - loss: 0.3660 - val_accuracy: 0.8182 - val_loss: 0.4733
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8368 - loss: 0.3710 - val_accuracy: 0.8182 - val_loss: 0.4638
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8626 - loss: 0.3357 - val_accuracy: 0.8312 - val_loss: 0.4603
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8544 - loss: 0.3508 - val_accuracy: 0.8182 - val_loss: 0.4606
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8325 - loss: 0.3591 - val_accuracy: 0.8377 - val_loss: 0.4650
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8602 - loss: 0.3323 - val_accuracy: 0.8117 - val_loss: 0.4661
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8446 - loss: 0.3591 - val_accuracy: 0.8247 - val_loss: 0.4658
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8492 - loss: 0.3413 - val_accuracy: 0.8247 - val_loss: 0.4654
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8356 - loss: 0.3487 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8473 - loss: 0.3496 - val_accuracy: 0.8182 - val_loss: 0.4829
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8652 - loss: 0.3410 - val_accuracy: 0.8312 - val_loss: 0.4718
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8801 - loss: 0.3091 - val_accuracy: 0.8247 - val_loss: 0.4718
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8589 - loss: 0.3316 - val_accuracy: 0.8247 - val_loss: 0.4811
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8691 - loss: 0.3190 - val_accuracy: 0.8247 - val_loss: 0.4760
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8472 - loss: 0.3452 - val_accuracy: 0.8247 - val_loss: 0.4809
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8801 - loss: 0.2919 - val_accuracy: 0.8312 - val_loss: 0.4801
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8558 - loss: 0.3342 - val_accuracy: 0.8247 - val_loss: 0.4859
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8497 - loss: 0.3333 - val_accuracy: 0.8182 - val_loss: 0.4792
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8561 - loss: 0.3125 - val_accuracy: 0.7987 - val_loss: 0.4913
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8596 - loss: 0.3301 - val_accuracy: 0.8247 - val_loss: 0.4792
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8626 - loss: 0.3260 - val_accuracy: 0.8182 - val_loss: 0.4835
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8532 - loss: 0.3155 - val_accuracy: 0.7922 - val_loss: 0.4926
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8522 - loss: 0.3294 - val_accuracy: 0.8247 - val_loss: 0.4893
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8539 - loss: 0.3222 - val_accuracy: 0.8247 - val_loss: 0.4820
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8859 - loss: 0.2960 - val_accuracy: 0.8117 - val_loss: 0.4916
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8522 - loss: 0.3456 - val_accuracy: 0.8117 - val_loss: 0.4986
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8690 - loss: 0.3201 - val_accuracy: 0.8247 - val_loss: 0.4887
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8740 - loss: 0.3015 - val_accuracy: 0.7987 - val_loss: 0.4875
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8530 - loss: 0.2933 - val_accuracy: 0.8052 - val_loss: 0.4899
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8805 - loss: 0.2926 - val_accuracy: 0.7922 - val_loss: 0.5210
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8642 - loss: 0.3091 - val_accuracy: 0.8312 - val_loss: 0.4984
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8720 - loss: 0.3123 - val_accuracy: 0.8312 - val_loss: 0.4929
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.2835 - val_accuracy: 0.8182 - val_loss: 0.5090
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8830 - loss: 0.3018 - val_accuracy: 0.7792 - val_loss: 0.5391
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8508 - loss: 0.3032 - val_accuracy: 0.8182 - val_loss: 0.5121
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8809 - loss: 0.2745 - val_accuracy: 0.7857 - val_loss: 0.5221
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8832 - loss: 0.2759 - val_accuracy: 0.8052 - val_loss: 0.5197
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8913 - loss: 0.2850 - val_accuracy: 0.7987 - val_loss: 0.5317
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8918 - loss: 0.2995 - val_accuracy: 0.8117 - val_loss: 0.5206
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8832 - loss: 0.2760 - val_accuracy: 0.8247 - val_loss: 0.5205
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8966 - loss: 0.2913 - val_accuracy: 0.7987 - val_loss: 0.5277
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.2965 - val_accuracy: 0.7857 - val_loss: 0.5228
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8874 - loss: 0.2947 - val_accuracy: 0.8052 - val_loss: 0.5368
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8843 - loss: 0.2867 - val_accuracy: 0.7987 - val_loss: 0.5452
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8992 - loss: 0.2569 - val_accuracy: 0.7727 - val_loss: 0.5527
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9086 - loss: 0.2406 - val_accuracy: 0.7922 - val_loss: 0.5345
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8919 - loss: 0.2890 - val_accuracy: 0.7792 - val_loss: 0.5508
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8887 - loss: 0.2615 - val_accuracy: 0.8182 - val_loss: 0.5336
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8892 - loss: 0.2571 - val_accuracy: 0.7857 - val_loss: 0.5664
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8939 - loss: 0.2591 - val_accuracy: 0.8117 - val_loss: 0.5374
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9044 - loss: 0.2673 - val_accuracy: 0.7857 - val_loss: 0.5756
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8939 - loss: 0.2762 - val_accuracy: 0.8052 - val_loss: 0.5438
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9003 - loss: 0.2585 - val_accuracy: 0.8117 - val_loss: 0.5384
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9012 - loss: 0.2492 - val_accuracy: 0.8117 - val_loss: 0.5494
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8866 - loss: 0.2698 - val_accuracy: 0.7857 - val_loss: 0.5594
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8972 - loss: 0.2448 - val_accuracy: 0.7987 - val_loss: 0.5640
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9025 - loss: 0.2446 - val_accuracy: 0.8052 - val_loss: 0.5466

In [110]:
def model_build(hp):

  model = Sequential()
  model.add(Dense(32, activation = 'relu', input_dim=8))

  for i in range(hp.Int('num_layer', min_value=1, max_value=10)):
    model.add(Dense(72, activation = 'relu'))

  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [111]:
tuner= kt.RandomSearch(model_build, objective = 'val_accuracy', max_trials = 5, directory= 'mydir', project_name = 'sumit1')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [112]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 24s

In [113]:
tuner.get_best_hyperparameters()[0].values

{'num_layer': 2}

In [114]:
tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [116]:
model.fit(x_train, y_train, epochs=100, initial_epoch=5, validation_data=(x_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8938 - loss: 0.2491 - val_accuracy: 0.7662 - val_loss: 0.5684
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8867 - loss: 0.2686 - val_accuracy: 0.8182 - val_loss: 0.5627
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9061 - loss: 0.2479 - val_accuracy: 0.7922 - val_loss: 0.5786
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9136 - loss: 0.2501 - val_accuracy: 0.7857 - val_loss: 0.5697
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8922 - loss: 0.2790 - val_accuracy: 0.7922 - val_loss: 0.5969
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9063 - loss: 0.2507 - val_accuracy: 0.7857 - val_loss: 0.5861
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9272 - loss: 0.2327 - val_accuracy: 0.8117 - val_loss: 0.5682
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9092 - loss: 0.2267 - val_accuracy: 0.7922 - val_loss: 0.5809
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9108 - loss: 0.2480 - val_accuracy: 0.7922 - val_loss: 0.5811
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.2271 - val_accuracy: 0.7857 - val_loss: 0.5726
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9203 - loss: 0.2418 - val_accuracy: 0.7792 - val_loss: 0.5875
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9210 - loss: 0.2490 - val_accuracy: 0.7922 - val_loss: 0.5884
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9106 - loss: 0.2561 - val_accuracy: 0.7922 - val_loss: 0.5840
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9217 - loss: 0.2155 - val_accuracy: 0.7857 - val_loss: 0.5966
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9019 - loss: 0.2296 - val_accuracy: 0.7987 - val_loss: 0.5995
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9224 - loss: 0.2096 - val_accuracy: 0.7857 - val_loss: 0.6317
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9156 - loss: 0.2267 - val_accuracy: 0.7857 - val_loss: 0.6183
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9196 - loss: 0.2135 - val_accuracy: 0.7987 - val_loss: 0.6300
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9239 - loss: 0.2146 - val_accuracy: 0.7857 - val_loss: 0.6304
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9339 - loss: 0.2265 - val_accuracy: 0.7857 - val_loss: 0.6307
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9288 - loss: 0.1957 - val_accuracy: 0.7792 - val_loss: 0.6094
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.2455 - val_accuracy: 0.7922 - val_loss: 0.6182
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9084 - loss: 0.2288 - val_accuracy: 0.7727 - val_loss: 0.6074
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9144 - loss: 0.2441 - val_accuracy: 0.7727 - val_loss: 0.6266
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9204 - loss: 0.2258 - val_accuracy: 0.7922 - val_loss: 0.6258
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9363 - loss: 0.1966 - val_accuracy: 0.7792 - val_loss: 0.6433
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9224 - loss: 0.2180 - val_accuracy: 0.7662 - val_loss: 0.6196
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9262 - loss: 0.2057 - val_accuracy: 0.7857 - val_loss: 0.6357
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9263 - loss: 0.1958 - val_accuracy: 0.7792 - val_loss: 0.6298
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9197 - loss: 0.2169 - val_accuracy: 0.7922 - val_loss: 0.6511
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9405 - loss: 0.1829 - val_accuracy: 0.7857 - val_loss: 0.6466
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9460 - loss: 0.1805 - val_accuracy: 0.7792 - val_loss: 0.6497
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9302 - loss: 0.2067 - val_accuracy: 0.7792 - val_loss: 0.6720
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9317 - loss: 0.1921 - val_accuracy: 0.7727 - val_loss: 0.6535
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1951 - val_accuracy: 0.7922 - val_loss: 0.6487
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9399 - loss: 0.1838 - val_accuracy: 0.7857 - val_loss: 0.6777
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9265 - loss: 0.1886 - val_accuracy: 0.7922 - val_loss: 0.6589
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9417 - loss: 0.1911 - val_accuracy: 0.7662 - val_loss: 0.6531
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9407 - loss: 0.1827 - val_accuracy: 0.7922 - val_loss: 0.6823
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9361 - loss: 0.1830 - val_accuracy: 0.7792 - val_loss: 0.6651
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1755 - val_accuracy: 0.7727 - val_loss: 0.6690
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9438 - loss: 0.1826 - val_accuracy: 0.7662 - val_loss: 0.6831
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9350 - loss: 0.1811 - val_accuracy: 0.7662 - val_loss: 0.6672
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9262 - loss: 0.1931 - val_accuracy: 0.7857 - val_loss: 0.7019
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9436 - loss: 0.1698 - val_accuracy: 0.7532 - val_loss: 0.7128
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9575 - loss: 0.1578 - val_accuracy: 0.7857 - val_loss: 0.6960
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9355 - loss: 0.1778 - val_accuracy: 0.7792 - val_loss: 0.7133
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9376 - loss: 0.1744 - val_accuracy: 0.7857 - val_loss: 0.6960
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9516 - loss: 0.1508 - val_accuracy: 0.7792 - val_loss: 0.7103
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9514 - loss: 0.1611 - val_accuracy: 0.7597 - val_loss: 0.7115
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9224 - loss: 0.1644 - val_accuracy: 0.7792 - val_loss: 0.7179
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9470 - loss: 0.1611 - val_accuracy: 0.7922 - val_loss: 0.7255
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9371 - loss: 0.1795 - val_accuracy: 0.7662 - val_loss: 0.7383
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9567 - loss: 0.1538 - val_accuracy: 0.7662 - val_loss: 0.7397
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9485 - loss: 0.1588 - val_accuracy: 0.7662 - val_loss: 0.7031
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9528 - loss: 0.1550 - val_accuracy: 0.7727 - val_loss: 0.7147
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9366 - loss: 0.1628 - val_accuracy: 0.7727 - val_loss: 0.7410
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9485 - loss: 0.1586 - val_accuracy: 0.7597 - val_loss: 0.7524
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9445 - loss: 0.1603 - val_accuracy: 0.7662 - val_loss: 0.7244
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9493 - loss: 0.1552 - val_accuracy: 0.7792 - val_loss: 0.7213
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9502 - loss: 0.1439 - val_accuracy: 0.7597 - val_loss: 0.7411
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9615 - loss: 0.1345 - val_accuracy: 0.7727 - val_loss: 0.7496
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9510 - loss: 0.1579 - val_accuracy: 0.7727 - val_loss: 0.7716
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9633 - loss: 0.1359 - val_accuracy: 0.7597 - val_loss: 0.7342
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1499 - val_accuracy: 0.7597 - val_loss: 0.7793
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9657 - loss: 0.1250 - val_accuracy: 0.7662 - val_loss: 0.7418
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9546 - loss: 0.1400 - val_accuracy: 0.7792 - val_loss: 0.7496
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9505 - loss: 0.1374 - val_accuracy: 0.7597 - val_loss: 0.7958
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9517 - loss: 0.1479 - val_accuracy: 0.7792 - val_loss: 0.8081
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9507 - loss: 0.1468 - val_accuracy: 0.7468 - val_loss: 0.8197
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9595 - loss: 0.1229 - val_accuracy: 0.7468 - val_loss: 0.8034
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9560 - loss: 0.1445 - val_accuracy: 0.7662 - val_loss: 0.8029
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9612 - loss: 0.1264 - val_accuracy: 0.7468 - val_loss: 0.7809
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9670 - loss: 0.1271 - val_accuracy: 0.7597 - val_loss: 0.7888
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9767 - loss: 0.1098 - val_accuracy: 0.7662 - val_loss: 0.7762
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9624 - loss: 0.1196 - val_accuracy: 0.7792 - val_loss: 0.7902
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9549 - loss: 0.1240 - val_accuracy: 0.7532 - val_loss: 0.8496
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9708 - loss: 0.1201 - val_accuracy: 0.7403 - val_loss: 0.8591
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9654 - loss: 0.1119 - val_accuracy: 0.7597 - val_loss: 0.7967
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9770 - loss: 0.1124 - val_accuracy: 0.7727 - val_loss: 0.8265
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1272 - val_accuracy: 0.7532 - val_loss: 0.7974
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9803 - loss: 0.1032 - val_accuracy: 0.7532 - val_loss: 0.8157
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9615 - loss: 0.1276 - val_accuracy: 0.7403 - val_loss: 0.8130
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9701 - loss: 0.1215 - val_accuracy: 0.7662 - val_loss: 0.8148
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9655 - loss: 0.1207 - val_accuracy: 0.7468 - val_loss: 0.8611
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1131 - val_accuracy: 0.7662 - val_loss: 0.8457
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9582 - loss: 0.1200 - val_accuracy: 0.7532 - val_loss: 0.8422
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9723 - loss: 0.1126 - val_accuracy: 0.7468 - val_loss: 0.8973
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9746 - loss: 0.0994 - val_accuracy: 0.7532 - val_loss: 0.8382
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.1063 - val_accuracy: 0.7597 - val_loss: 0.8359
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9787 - loss: 0.0969 - val_accuracy: 0.7403 - val_loss: 0.8847
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9783 - loss: 0.1013 - val_accuracy: 0.7532 - val_loss: 0.8425
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9741 - loss: 0.0955 - val_accuracy: 0.7662 - val_loss: 0.8571
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9710 - loss: 0.1076 - val_accuracy: 0.7662 - val_loss: 0.8741
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9778 - loss: 0.0960 - val_accuracy: 0.7727 - val_loss: 0.8510

In [140]:
def build_model(hp):

  model = Sequential()


  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('unit'+str(i), min_value=8, max_value=128, step =8),
      activation = hp.Choice ('activation'+ str(i), values = ['relu', 'tanh','sigmoid']),
                      input_dim = 8))
      model.add(Dropout(hp.Choice('Dropuot'+ str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5,0.6, 0.7])))
  else:
     model.add(Dense(hp.Int('unit'+str(i), min_value=8, max_value=128, step =8),
     activation = hp.Choice ('activation'+ str(i), values = ['relu', 'tanh','sigmoid']),
                      ))
     model.add(Dropout(hp.Choice('Dropuot'+ str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5,0.6, 0.7])))

  counter+=1
  model.add(Dense(1,activation = 'sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer', values=['rmsprop','adam','sgd','nadam']),
                loss = 'binary_crossentropy',
                metrics = ['accuracy'])
  return model

In [142]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name = 'sumit4'
                        )

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [143]:
# tuner.search(x_train, y_train, epochs = 5, validation_data(x_test, y_test))
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Trial 3 Complete [00h 00m 06s]
val_accuracy: 0.6948052048683167

Best val_accuracy So Far: 0.6948052048683167
Total elapsed time: 00h 00m 15s

In [145]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'unit0': 120,
 'activation0': 'sigmoid',
 'Dropuot0': 0.5,
 'optimizer': 'nadam'}

In [146]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 15 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [147]:
model.fit(x_train, y_train, batch_size = 3, epochs=100, initial_epoch=5, validation_data=(x_test, y_test) )

Epoch 6/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5621 - loss: 0.7463 - val_accuracy: 0.6948 - val_loss: 0.5675
Epoch 7/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6106 - loss: 0.6644 - val_accuracy: 0.7013 - val_loss: 0.5244
Epoch 8/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6366 - loss: 0.6302 - val_accuracy: 0.7727 - val_loss: 0.4846
Epoch 9/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6924 - loss: 0.5951 - val_accuracy: 0.7792 - val_loss: 0.4644
Epoch 10/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7147 - loss: 0.5665 - val_accuracy: 0.7857 - val_loss: 0.4544
Epoch 11/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7348 - loss: 0.5353 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 12/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7577 - loss: 0.5002 - val_accuracy: 0.7727 - val_loss: 0.4684
Epoch 13/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7377 - loss: 0.5468 - val_accuracy: 0.8117 - val_loss: 0.4449
Epoch 14/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7498 - loss: 0.5361 - val_accuracy: 0.8052 - val_loss: 0.4423
Epoch 15/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7468 - loss: 0.5262 - val_accuracy: 0.8182 - val_loss: 0.4318
Epoch 16/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7493 - loss: 0.5404 - val_accuracy: 0.8052 - val_loss: 0.4334
Epoch 17/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7267 - loss: 0.5211 - val_accuracy: 0.8182 - val_loss: 0.4249
Epoch 18/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7702 - loss: 0.5161 - val_accuracy: 0.7987 - val_loss: 0.4373
Epoch 19/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7104 - loss: 0.5414 - val_accuracy: 0.8117 - val_loss: 0.4287
Epoch 20/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7517 - loss: 0.5041 - val_accuracy: 0.8117 - val_loss: 0.4307
Epoch 21/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7430 - loss: 0.5223 - val_accuracy: 0.8182 - val_loss: 0.4252
Epoch 22/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7577 - loss: 0.4651 - val_accuracy: 0.7857 - val_loss: 0.4411
Epoch 23/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7445 - loss: 0.5233 - val_accuracy: 0.8117 - val_loss: 0.4246
Epoch 24/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7820 - loss: 0.4727 - val_accuracy: 0.8182 - val_loss: 0.4219
Epoch 25/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7991 - loss: 0.4754 - val_accuracy: 0.8052 - val_loss: 0.4313
Epoch 26/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7384 - loss: 0.5185 - val_accuracy: 0.8182 - val_loss: 0.4246
Epoch 27/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7610 - loss: 0.4883 - val_accuracy: 0.8117 - val_loss: 0.4207
Epoch 28/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7591 - loss: 0.4824 - val_accuracy: 0.8052 - val_loss: 0.4274
Epoch 29/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7522 - loss: 0.4912 - val_accuracy: 0.8117 - val_loss: 0.4331
Epoch 30/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7640 - loss: 0.5162 - val_accuracy: 0.8117 - val_loss: 0.4215
Epoch 31/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.7678 - loss: 0.4910 - val_accuracy: 0.8052 - val_loss: 0.4281
Epoch 32/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7419 - loss: 0.5210 - val_accuracy: 0.8182 - val_loss: 0.4216
Epoch 33/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7691 - loss: 0.4896 - val_accuracy: 0.8052 - val_loss: 0.4251
Epoch 34/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7796 - loss: 0.4601 - val_accuracy: 0.8052 - val_loss: 0.4293
Epoch 35/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7378 - loss: 0.5342 - val_accuracy: 0.7987 - val_loss: 0.4420
Epoch 36/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7146 - loss: 0.5103 - val_accuracy: 0.8117 - val_loss: 0.4206
Epoch 37/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7553 - loss: 0.5033 - val_accuracy: 0.8052 - val_loss: 0.4230
Epoch 38/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7753 - loss: 0.4503 - val_accuracy: 0.8117 - val_loss: 0.4291
Epoch 39/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7685 - loss: 0.4954 - val_accuracy: 0.8247 - val_loss: 0.4199
Epoch 40/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7243 - loss: 0.5264 - val_accuracy: 0.8117 - val_loss: 0.4248
Epoch 41/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7517 - loss: 0.5008 - val_accuracy: 0.8182 - val_loss: 0.4236
Epoch 42/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7634 - loss: 0.4847 - val_accuracy: 0.8182 - val_loss: 0.4211
Epoch 43/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7795 - loss: 0.4766 - val_accuracy: 0.7922 - val_loss: 0.4337
Epoch 44/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7557 - loss: 0.5087 - val_accuracy: 0.8052 - val_loss: 0.4232
Epoch 45/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7827 - loss: 0.4541 - val_accuracy: 0.7987 - val_loss: 0.4337
Epoch 46/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7768 - loss: 0.4922 - val_accuracy: 0.7922 - val_loss: 0.4356
Epoch 47/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7616 - loss: 0.4887 - val_accuracy: 0.8182 - val_loss: 0.4325
Epoch 48/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7884 - loss: 0.4755 - val_accuracy: 0.7922 - val_loss: 0.4389
Epoch 49/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7497 - loss: 0.4756 - val_accuracy: 0.7922 - val_loss: 0.4411
Epoch 50/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7461 - loss: 0.4938 - val_accuracy: 0.8182 - val_loss: 0.4256
Epoch 51/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7769 - loss: 0.4549 - val_accuracy: 0.7987 - val_loss: 0.4309
Epoch 52/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7765 - loss: 0.4592 - val_accuracy: 0.7922 - val_loss: 0.4282
Epoch 53/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7408 - loss: 0.5178 - val_accuracy: 0.8182 - val_loss: 0.4262
Epoch 54/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7618 - loss: 0.4773 - val_accuracy: 0.8182 - val_loss: 0.4223
Epoch 55/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7606 - loss: 0.4842 - val_accuracy: 0.8182 - val_loss: 0.4256
Epoch 56/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7812 - loss: 0.4491 - val_accuracy: 0.8182 - val_loss: 0.4374
Epoch 57/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7847 - loss: 0.4696 - val_accuracy: 0.8117 - val_loss: 0.4347
Epoch 58/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7946 - loss: 0.4717 - val_accuracy: 0.8182 - val_loss: 0.4276
Epoch 59/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7497 - loss: 0.5075 - val_accuracy: 0.8117 - val_loss: 0.4242
Epoch 60/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7776 - loss: 0.4568 - val_accuracy: 0.8182 - val_loss: 0.4265
Epoch 61/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7623 - loss: 0.4674 - val_accuracy: 0.8117 - val_loss: 0.4314
Epoch 62/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7808 - loss: 0.4539 - val_accuracy: 0.8052 - val_loss: 0.4456
Epoch 63/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7759 - loss: 0.4454 - val_accuracy: 0.8052 - val_loss: 0.4413
Epoch 64/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7696 - loss: 0.4780 - val_accuracy: 0.7922 - val_loss: 0.4310
Epoch 65/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7833 - loss: 0.4614 - val_accuracy: 0.7987 - val_loss: 0.4414
Epoch 66/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8036 - loss: 0.4212 - val_accuracy: 0.8117 - val_loss: 0.4373
Epoch 67/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7776 - loss: 0.4376 - val_accuracy: 0.8117 - val_loss: 0.4350
Epoch 68/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7983 - loss: 0.4404 - val_accuracy: 0.8117 - val_loss: 0.4467
Epoch 69/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7710 - loss: 0.4553 - val_accuracy: 0.8052 - val_loss: 0.4410
Epoch 70/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8114 - loss: 0.4415 - val_accuracy: 0.8117 - val_loss: 0.4337
Epoch 71/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7660 - loss: 0.4869 - val_accuracy: 0.8052 - val_loss: 0.4404
Epoch 72/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7704 - loss: 0.4887 - val_accuracy: 0.8052 - val_loss: 0.4374
Epoch 73/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7904 - loss: 0.4393 - val_accuracy: 0.8052 - val_loss: 0.4387
Epoch 74/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7246 - loss: 0.4887 - val_accuracy: 0.8052 - val_loss: 0.4480
Epoch 75/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7700 - loss: 0.4680 - val_accuracy: 0.8117 - val_loss: 0.4375
Epoch 76/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7732 - loss: 0.4586 - val_accuracy: 0.8052 - val_loss: 0.4406
Epoch 77/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7619 - loss: 0.4569 - val_accuracy: 0.8117 - val_loss: 0.4330
Epoch 78/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7654 - loss: 0.4999 - val_accuracy: 0.8052 - val_loss: 0.4379
Epoch 79/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7738 - loss: 0.4869 - val_accuracy: 0.8052 - val_loss: 0.4336
Epoch 80/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7590 - loss: 0.5020 - val_accuracy: 0.8052 - val_loss: 0.4348
Epoch 81/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7510 - loss: 0.4693 - val_accuracy: 0.8052 - val_loss: 0.4475
Epoch 82/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8174 - loss: 0.4264 - val_accuracy: 0.8052 - val_loss: 0.4557
Epoch 83/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7593 - loss: 0.4586 - val_accuracy: 0.7987 - val_loss: 0.4430
Epoch 84/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7978 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4445
Epoch 85/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7952 - loss: 0.4576 - val_accuracy: 0.7922 - val_loss: 0.4408
Epoch 86/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7830 - loss: 0.4622 - val_accuracy: 0.7987 - val_loss: 0.4406
Epoch 87/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7821 - loss: 0.4406 - val_accuracy: 0.8052 - val_loss: 0.4410
Epoch 88/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7769 - loss: 0.4461 - val_accuracy: 0.8052 - val_loss: 0.4391
Epoch 89/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7799 - loss: 0.4584 - val_accuracy: 0.8052 - val_loss: 0.4346
Epoch 90/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7623 - loss: 0.4773 - val_accuracy: 0.8052 - val_loss: 0.4406
Epoch 91/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7830 - loss: 0.4493 - val_accuracy: 0.8052 - val_loss: 0.4437
Epoch 92/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7426 - loss: 0.4973 - val_accuracy: 0.8052 - val_loss: 0.4369
Epoch 93/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7789 - loss: 0.4643 - val_accuracy: 0.8052 - val_loss: 0.4461
Epoch 94/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7661 - loss: 0.4845 - val_accuracy: 0.7987 - val_loss: 0.4370
Epoch 95/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7740 - loss: 0.4556 - val_accuracy: 0.7922 - val_loss: 0.4435
Epoch 96/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7718 - loss: 0.4745 - val_accuracy: 0.7922 - val_loss: 0.4477
Epoch 97/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7526 - loss: 0.4570 - val_accuracy: 0.7857 - val_loss: 0.4480
Epoch 98/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7881 - loss: 0.4536 - val_accuracy: 0.7922 - val_loss: 0.4417
Epoch 99/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7656 - loss: 0.4702 - val_accuracy: 0.8052 - val_loss: 0.4532
Epoch 100/100
205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7583 - loss: 0.4885 - val_accuracy: 0.7987 - val_loss: 0.4481

In [151]:
! git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/